import { FilterType } from "@/types";

export enum PAYMENT_METHOD {
  COD = "cod",
  QR = "qr",
  VNPAY_ATM = "vnpay_atm",
  CARD = "card",
  ZALOPAY = "zalopay",
  MOMO = "momo",
  VNPAY = "vnpay",
}
export const MAX_WIDTH_MOBILE = 767;
export const paymentMethods = [
  {
    method: PAYMENT_METHOD.COD,
    label: " Thanh toán tiền mặt khi nhận hàng",
    image: "/icons/png/cod.webp",
    disabled: false,
  },
  {
    method: PAYMENT_METHOD.QR,
    label: "Thanh toán bằng chuyển khoản (QR Code)",
    image: "/icons/png/qr.webp",
    disabled: true,
  },
  {
    method: PAYMENT_METHOD.VNPAY_ATM,
    label: "Thanh toán bằng thẻ ATM nội địa và tài khoản ngân hàng",
    image: "/icons/png/vnpay_atm.webp",
    disabled: true,
  },
  {
    method: PAYMENT_METHOD.CARD,
    label:
      "Thanh toán bằng thẻ quốc tế Visa, Master, JCB, AMEX (GooglePay, ApplePay)",
    image: "/icons/png/card.webp",
    disabled: true,
  },
  {
    method: PAYMENT_METHOD.ZALOPAY,
    label: "Thanh toán bằng ZaloPay",
    image: "/icons/png/zalopay.webp",
    disabled: true,
  },
  {
    method: PAYMENT_METHOD.MOMO,
    label: "Thanh toán bằng MoMo",
    image: "/icons/png/momo.webp",
    disabled: true,
  },
  {
    method: PAYMENT_METHOD.VNPAY,
    label: "Thanh toán bằng VNPAY",
    image: "/icons/png/vnpay.webp",
    disabled: true,
  },
];

export const cities = [
  {
    id: 23,
    name: "Hồ Chí Minh",
    cityId: "23",
    locationSlug: "ho-chi-minh",
    idName: "23-Hồ Chí Minh",
  },
  {
    id: 26,
    name: "Hà Nội",
    cityId: "26",
    locationSlug: "ha-noi",
    idName: "26-Hà Nội",
  },
  {
    id: 17,
    name: "Đà Nẵng",
    cityId: "17",
    locationSlug: "da-nang",
    idName: "17-Đà Nẵng",
  },
  {
    id: 14,
    name: "Cần Thơ",
    cityId: "14",
    locationSlug: "can-tho",
    idName: "14-Cần Thơ",
  },
  {
    id: 28,
    name: "Hải Phòng",
    cityId: "28",
    locationSlug: "hai-phong",
    idName: "28-Hải Phòng",
  },
  {
    id: 1,
    name: "Tỉnh An Giang",
    cityId: "1",
    locationSlug: "tinh-an-giang",
    idName: "1-Tỉnh An Giang",
  },
  {
    id: 9,
    name: "Tỉnh Bà Rịa - Vũng Tàu",
    cityId: "9",
    locationSlug: "tinh-ba-ria---vung-tau",
    idName: "9-Tỉnh Bà Rịa - Vũng Tàu",
  },
  {
    id: 4,
    name: "Tỉnh Bắc Giang",
    cityId: "4",
    locationSlug: "tinh-bac-giang",
    idName: "4-Tỉnh Bắc Giang",
  },
  {
    id: 5,
    name: "Tỉnh Bắc Kạn",
    cityId: "5",
    locationSlug: "tinh-bac-kan",
    idName: "5-Tỉnh Bắc Kạn",
  },
  {
    id: 6,
    name: "Tỉnh Bạc Liêu",
    cityId: "6",
    locationSlug: "tinh-bac-lieu",
    idName: "6-Tỉnh Bạc Liêu",
  },
  {
    id: 7,
    name: "Tỉnh Bắc Ninh",
    cityId: "7",
    locationSlug: "tinh-bac-ninh",
    idName: "7-Tỉnh Bắc Ninh",
  },
  {
    id: 10,
    name: "Tỉnh Bến Tre",
    cityId: "10",
    locationSlug: "tinh-ben-tre",
    idName: "10-Tỉnh Bến Tre",
  },
  {
    id: 3,
    name: "Tỉnh Bình Định",
    cityId: "3",
    locationSlug: "tinh-binh-dinh",
    idName: "3-Tỉnh Bình Định",
  },
  {
    id: 2,
    name: "Tỉnh Bình Dương",
    cityId: "2",
    locationSlug: "tinh-binh-duong",
    idName: "2-Tỉnh Bình Dương",
  },
  {
    id: 8,
    name: "Tỉnh Bình Phước",
    cityId: "8",
    locationSlug: "tinh-binh-phuoc",
    idName: "8-Tỉnh Bình Phước",
  },
  {
    id: 11,
    name: "Tỉnh Bình Thuận",
    cityId: "11",
    locationSlug: "tinh-binh-thuan",
    idName: "11-Tỉnh Bình Thuận",
  },
  {
    id: 13,
    name: "Tỉnh Cà Mau",
    cityId: "13",
    locationSlug: "tinh-ca-mau",
    idName: "13-Tỉnh Cà Mau",
  },
  {
    id: 12,
    name: "Tỉnh Cao Bằng",
    cityId: "12",
    locationSlug: "tinh-cao-bang",
    idName: "12-Tỉnh Cao Bằng",
  },
  {
    id: 16,
    name: "Tỉnh Đắk Lắk",
    cityId: "16",
    locationSlug: "tinh-dak-lak",
    idName: "16-Tỉnh Đắk Lắk",
  },
  {
    id: 19,
    name: "Tỉnh Đăk Nông",
    cityId: "19",
    locationSlug: "tinh-dak-nong",
    idName: "19-Tỉnh Đăk Nông",
  },
  {
    id: 15,
    name: "Tỉnh Điện Biên",
    cityId: "15",
    locationSlug: "tinh-dien-bien",
    idName: "15-Tỉnh Điện Biên",
  },
  {
    id: 18,
    name: "Tỉnh Đồng Nai",
    cityId: "18",
    locationSlug: "tinh-dong-nai",
    idName: "18-Tỉnh Đồng Nai",
  },
  {
    id: 20,
    name: "Tỉnh Đồng Tháp",
    cityId: "20",
    locationSlug: "tinh-dong-thap",
    idName: "20-Tỉnh Đồng Tháp",
  },
  {
    id: 21,
    name: "Tỉnh Gia Lai",
    cityId: "21",
    locationSlug: "tinh-gia-lai",
    idName: "21-Tỉnh Gia Lai",
  },
  {
    id: 25,
    name: "Tỉnh Hà Giang",
    cityId: "25",
    locationSlug: "tinh-ha-giang",
    idName: "25-Tỉnh Hà Giang",
  },
  {
    id: 27,
    name: "Tỉnh Hà Nam",
    cityId: "27",
    locationSlug: "tinh-ha-nam",
    idName: "27-Tỉnh Hà Nam",
  },
  {
    id: 29,
    name: "Tỉnh Hà Tĩnh",
    cityId: "29",
    locationSlug: "tinh-ha-tinh",
    idName: "29-Tỉnh Hà Tĩnh",
  },
  {
    id: 24,
    name: "Tỉnh Hải Dương",
    cityId: "24",
    locationSlug: "tinh-hai-duong",
    idName: "24-Tỉnh Hải Dương",
  },
  {
    id: 32,
    name: "Tỉnh Hậu Giang",
    cityId: "32",
    locationSlug: "tinh-hau-giang",
    idName: "32-Tỉnh Hậu Giang",
  },
  {
    id: 22,
    name: "Tỉnh Hòa Bình",
    cityId: "22",
    locationSlug: "tinh-hoa-binh",
    idName: "22-Tỉnh Hòa Bình",
  },
  {
    id: 33,
    name: "Tỉnh Hưng Yên",
    cityId: "33",
    locationSlug: "tinh-hung-yen",
    idName: "33-Tỉnh Hưng Yên",
  },
  {
    id: 35,
    name: "Tỉnh Khánh Hòa",
    cityId: "35",
    locationSlug: "tinh-khanh-hoa",
    idName: "35-Tỉnh Khánh Hòa",
  },
  {
    id: 34,
    name: "Tỉnh Kiên Giang",
    cityId: "34",
    locationSlug: "tinh-kien-giang",
    idName: "34-Tỉnh Kiên Giang",
  },
  {
    id: 36,
    name: "Tỉnh Kon Tum",
    cityId: "36",
    locationSlug: "tinh-kon-tum",
    idName: "36-Tỉnh Kon Tum",
  },
  {
    id: 39,
    name: "Tỉnh Lai Châu",
    cityId: "39",
    locationSlug: "tinh-lai-chau",
    idName: "39-Tỉnh Lai Châu",
  },
  {
    id: 40,
    name: "Tỉnh Lâm Đồng",
    cityId: "40",
    locationSlug: "tinh-lam-dong",
    idName: "40-Tỉnh Lâm Đồng",
  },
  {
    id: 41,
    name: "Tỉnh Lạng Sơn",
    cityId: "41",
    locationSlug: "tinh-lang-son",
    idName: "41-Tỉnh Lạng Sơn",
  },
  {
    id: 38,
    name: "Tỉnh Lào Cai",
    cityId: "38",
    locationSlug: "tinh-lao-cai",
    idName: "38-Tỉnh Lào Cai",
  },
  {
    id: 37,
    name: "Tỉnh Long An",
    cityId: "37",
    locationSlug: "tinh-long-an",
    idName: "37-Tỉnh Long An",
  },
  {
    id: 44,
    name: "Tỉnh Nam Định",
    cityId: "44",
    locationSlug: "tinh-nam-dinh",
    idName: "44-Tỉnh Nam Định",
  },
  {
    id: 42,
    name: "Tỉnh Nghệ An",
    cityId: "42",
    locationSlug: "tinh-nghe-an",
    idName: "42-Tỉnh Nghệ An",
  },
  {
    id: 43,
    name: "Tỉnh Ninh Bình",
    cityId: "43",
    locationSlug: "tinh-ninh-binh",
    idName: "43-Tỉnh Ninh Bình",
  },
  {
    id: 45,
    name: "Tỉnh Ninh Thuận",
    cityId: "45",
    locationSlug: "tinh-ninh-thuan",
    idName: "45-Tỉnh Ninh Thuận",
  },
  {
    id: 46,
    name: "Tỉnh Phú Thọ",
    cityId: "46",
    locationSlug: "tinh-phu-tho",
    idName: "46-Tỉnh Phú Thọ",
  },
  {
    id: 47,
    name: "Tỉnh Phú Yên",
    cityId: "47",
    locationSlug: "tinh-phu-yen",
    idName: "47-Tỉnh Phú Yên",
  },
  {
    id: 48,
    name: "Tỉnh Quảng Bình",
    cityId: "48",
    locationSlug: "tinh-quang-binh",
    idName: "48-Tỉnh Quảng Bình",
  },
  {
    id: 51,
    name: "Tỉnh Quảng Nam",
    cityId: "51",
    locationSlug: "tinh-quang-nam",
    idName: "51-Tỉnh Quảng Nam",
  },
  {
    id: 50,
    name: "Tỉnh Quảng Ngãi",
    cityId: "50",
    locationSlug: "tinh-quang-ngai",
    idName: "50-Tỉnh Quảng Ngãi",
  },
  {
    id: 49,
    name: "Tỉnh Quảng Ninh",
    cityId: "49",
    locationSlug: "tinh-quang-ninh",
    idName: "49-Tỉnh Quảng Ninh",
  },
  {
    id: 52,
    name: "Tỉnh Quảng Trị",
    cityId: "52",
    locationSlug: "tinh-quang-tri",
    idName: "52-Tỉnh Quảng Trị",
  },
  {
    id: 54,
    name: "Tỉnh Sóc Trăng",
    cityId: "54",
    locationSlug: "tinh-soc-trang",
    idName: "54-Tỉnh Sóc Trăng",
  },
  {
    id: 53,
    name: "Tỉnh Sơn La",
    cityId: "53",
    locationSlug: "tinh-son-la",
    idName: "53-Tỉnh Sơn La",
  },
  {
    id: 58,
    name: "Tỉnh Tây Ninh",
    cityId: "58",
    locationSlug: "tinh-tay-ninh",
    idName: "58-Tỉnh Tây Ninh",
  },
  {
    id: 55,
    name: "Tỉnh Thái Bình",
    cityId: "55",
    locationSlug: "tinh-thai-binh",
    idName: "55-Tỉnh Thái Bình",
  },
  {
    id: 59,
    name: "Tỉnh Thái Nguyên",
    cityId: "59",
    locationSlug: "tinh-thai-nguyen",
    idName: "59-Tỉnh Thái Nguyên",
  },
  {
    id: 57,
    name: "Tỉnh Thanh Hóa",
    cityId: "57",
    locationSlug: "tinh-thanh-hoa",
    idName: "57-Tỉnh Thanh Hóa",
  },
  {
    id: 31,
    name: "Tỉnh Thừa Thiên Huế",
    cityId: "31",
    locationSlug: "tinh-thua-thien-hue",
    idName: "31-Tỉnh Thừa Thiên Huế",
  },
  {
    id: 56,
    name: "Tỉnh Tiền Giang",
    cityId: "56",
    locationSlug: "tinh-tien-giang",
    idName: "56-Tỉnh Tiền Giang",
  },
  {
    id: 61,
    name: "Tỉnh Trà Vinh",
    cityId: "61",
    locationSlug: "tinh-tra-vinh",
    idName: "61-Tỉnh Trà Vinh",
  },
  {
    id: 60,
    name: "Tỉnh Tuyên Quang",
    cityId: "60",
    locationSlug: "tinh-tuyen-quang",
    idName: "60-Tỉnh Tuyên Quang",
  },
  {
    id: 62,
    name: "Tỉnh Vĩnh Long",
    cityId: "62",
    locationSlug: "tinh-vinh-long",
    idName: "62-Tỉnh Vĩnh Long",
  },
  {
    id: 63,
    name: "Tỉnh Vĩnh Phúc",
    cityId: "63",
    locationSlug: "tinh-vinh-phuc",
    idName: "63-Tỉnh Vĩnh Phúc",
  },
  {
    id: 64,
    name: "Tỉnh Yên Bái",
    cityId: "64",
    locationSlug: "tinh-yen-bai",
    idName: "64-Tỉnh Yên Bái",
  },
];
export const INIT_FILTERS: FilterType = {
  brand: [],
  category: [],
  country: [],
  price: [],
  rating: null,
};
